#!/usr/bin/env bash
# script that installs nginx on web server

apt-get -y update
apt-get -y install nginx

service nginx start
bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx reload
